### ISSUE TITLE
CSS issues on deployment

### ISSUE THREAD

**Issue by jacobmort** [PermanentLoss/permanentloss#21]
<img width="1792" alt="Screen Shot 2020-10-18 at 10 17 40 AM" src="https://user-images.githubusercontent.com/361696/96375585-af2c0e80-112e-11eb-8bd2-4e90f3a2e06c.png">

(input width issue happens locally too)

**Comment by andrekorol** [comment]
Might be better to replace that Header component altogether.

**Comment by andrekorol** [comment]
PR #35 fixed the header but, now the body is messed up: [Netlify Preview](https://5f8cddc3700ce5000739d58b--stoic-noether-907ad0.netlify.app/).

I think the problem is with the [local styled-components](https://github.com/PermanentLoss/permanentloss/blob/main/interface/packages/react-app/src/components/index.jsx), as was the problem in the header. [from here](https://github.com/PermanentLoss/permanentloss/blob/main/interface/packages/react-app/src/components/index.jsx).

We'll probably have to switch almost everything to React Bootstrap to get everything working while at the same time getting rid of issue #29.
